export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const CONNECTED_USER = "CONNECTED_USER";
export const USER_REGISTER = "USER_REGISTER";
export const USER_LOGIN = "USER_LOGIN";
export const GET_USER = "GET_USER";
